baseURL = "/"
languageCode = "en-us"
title = "blog.cjcocokrisp.dev"
theme = "re-terminal"


[params]
  themeColor = "red"
  favicon = "favicon.ico"
  readingTime = true
  

  # [params.banner]
  # dismissible = false
  # text = "Check it out on GitHub"
  # url = "https://github.com/mirus-ua/hugo-theme-re-terminal"

[languages]
  [languages.en.params]
    languageName = "English"
    title = "blog.cjcocokrisp.dev"
    owner = "Christopher Coco"
    keywords = "Development, Technology, Gaming, Software Engineering, Open Source, Cloud Native, Kubernetes, Argo CD"
    copyright = "(c) 2026 Christopher Coco. All Rights Reserved."

  [languages.en.params.logo]
    logoText = "blog.cjcocokrisp.dev"

  [[languages.en.menu.main]]
    indentifer = "home"
    name = "Home"
    url = "/" 

[[languages.en.menu.main]]
    indentifer = "about"
    name = "About"
    url = "/about" 

  [[languages.en.menu.main]]
    indentifer = "posts"
    name = "Posts"
    url = "/list" 

  [[languages.en.menu.main]]
    indentifer = "return"
    name = "Return to Main Site"
    url = "https://www.cjcocokrisp.dev"
